:docinfo1:
:linkcss:
:stylesdir: asciidoc
:scriptsdir: asciidoc
:stylesheet: master.css
:toc2:
:toclevels: 3
:numbered:

= Glossary

include::sitemap.ascinc[]

This page gives a short description of many terms related to the Holy Gradle and its use with Artifactory.  Glossary entries may link to other pages for more information.

[glossary]
== Glossary

[glossary]
[[gloss-build-management]] Build management::
    In this documentation, build management means controlling how input forms of software (like C++ source files) are converted to output forms (like DLLs or EXEs).  This usually means using a tool like Unix +make+, Microsoft's MSBuild, or the Ant tool for Java--or gloss:gradle[].  The gloss:holygradle[] does not use gloss:gradle[]'s build management to control the details of building a Visual Studio solution, because Visual Studio already does that.  It only uses it to connect the tasks involved in getting and publishing modules.
[[gloss-dependency-management]] Dependency management::
    Managing information and tasks related to software modules which depend on each other.  In the context of gloss:gradle[] and gloss:artifactory[], module metadata includes the name of the module and its publisher (group), the version of the module, and a list of dependencies on other modules.  The most basic tasks are: getting all dependencies for a module you want to build; and publishing that module with metadata, after it is built.
[[gloss-gradle]] Gradle::
    An open source tool for gloss:dependency-management[] and gloss:build-management[].  Here "dependency management" means getting and publishing versioned software modules, mostly binary: Gradle modules components which your project uses, modules which those modules use, and so on; and it automatically finds version conflicts.  The "build management" part is similar to systems like Unix +make+, Microsoft's MSBuild, or the Ant tool for Java: you describe tasks and connections between them, and Gradle works out which tasks to run, in which order.
[[gloss-holygradle]] Holy Gradle::
    A set of gloss:gradle[] plugins which extend it to cover: using passwords store in the Windows Credential Manager; getting source code from Mercurial or Subversion; getting and publishing dependencies with many files (packed as ZIP files); and deleting temporary publications from Artifactory.  There are other features with minimal support: building with Visual Studio; running unit tests.