:docinfo1:
:linkcss:
:stylesdir: asciidoc
:scriptsdir: asciidoc
:stylesheet: master.css
:toc2:
:toclevels: 3
:numbered:

= Reference

include::sitemap.ascinc[]

This page ... *TODO* 

TODO: http://localwiki/Gradle#What_is_it.3F (link to release notes, gradle_what_where_how.xlsx, Gradle_High_Level_Map.pptx (list of plugins))

TODO: http://localwiki/Artifactory#HTTPS_Access (details of explicit setup -- some bits local, some general)

TODO: http://localwiki/Gradle_Cookbook

Following is an expanded version of the diagram in the link:overview.html ...

.gloss:holygradle[] component dependencies
[caption="Figure {counter:figureindex}: "]
[graphviz,reference_holygradle_components.svg,dot,svg]
--
digraph {
    ranksep=0.4
    fontsize=12
    node [shape=box, margin="0.04,0.04", height=0.3, fontsize=12]
    edge [fontsize=12]
    compound=true

    subgraph cluster_project {
        label="Your project"

        cluster_project_source [shape=point,margin="0.0",style=invis]
        cluster_project_sink [shape=point,margin="0.0",style=invis]
        cluster_project_source -> {

            //{ rank=same
                build [label="build.gradle", shape=note]
                gw [label="gw.bat", color=darkgreen, fontcolor=darkgreen, style=diagonals]
            //}
            wrapper [label="Gradle\nwrapper", color=darkgreen, fontcolor=darkgreen, style=diagonals]

        } -> cluster_project_sink [style=invis,minlen=0]

    }

    subgraph cluster_plugins {
        label="Holy Gradle Plugins"

        cluster_plugins_source [shape=point,margin="0.0",style=invis]
        cluster_plugins_sink [shape=point,margin="0.0",style=invis]
        cluster_plugins_source -> {

            { rank=same
                afym [label="artifactory-manager"]
                stamper [color=grey, fontcolor=grey, style=dashed]
            } -> { rank=same
                intrepid
                myc [label="my-credentials"]
                devenv [color=grey, fontcolor=grey, style=dashed]
                ut [label="unit-test", color=grey, fontcolor=grey, style=dashed]
            } -> { rank=same
                cgc [label="custom-gradle-core"]
                cred_store [label="credential-store.exe"]
            } [style=invis]

        } -> cluster_plugins_sink [style=invis,minlen=0]

        intrepid -> cgc [headport=n]
        myc -> cgc [headport=n]
        devenv -> cgc [headport=n]
        ut -> cgc [headport=n]
        intrepid -> cred_store

    }

    build -> afym [lhead=cluster_plugins, label="specifies"]

    build -> gw [label="input to", style=dashed]//, minlen=0]
    gw -> wrapper [label="runs"]


    subgraph cluster_kits {
        label="Starter ZIP files"

        cluster_kits_source [shape=point,margin="0.0",style=invis]
        cluster_kits_sink [shape=point,margin="0.0",style=invis]
        cluster_kits_source -> {

            https_kit [label="https-setup-kit"]
            wsk [label="wrapper-starter-kit"]

        } -> cluster_kits_sink [style=invis,minlen=0]
    }

    subgraph cluster_distro {
        label="Holy Gradle\nCustom Distribution"

        cluster_distro_source [shape=point,margin="0.0",style=invis]
        cluster_distro_sink [shape=point,margin="0.0",style=invis]
        cluster_distro_source -> {

            custom_gradle [label="custom-gradle"]

            node [color=darkgreen, fontcolor=darkgreen, style=diagonals]
            Gradle [label="Gradle 1.4"]
            Groovy [label="Groovy 1.8"]

        } -> cluster_distro_sink [style=invis,minlen=0]

        wsk -> custom_gradle
        cgc -> custom_gradle [weight=5]
        wrapper -> custom_gradle [label="downloads\n& runs"]
        custom_gradle -> cgc [lhead=cluster_plugins, label="downloads", constraint=false]
    }

    subgraph cluster_tools {
        label="Separate tools"

        cluster_tools_source [shape=point,margin="0.0",style=invis]
        cluster_tools_sink [shape=point,margin="0.0",style=invis]
        cluster_tools_source -> {

            node [color=darkgreen, fontcolor=darkgreen, style=diagonals]
            sevenzip [label="7zip.exe"]
            hg [label="hg.exe"]
            svn [label="svn"]
            VS [label="Visual Studio"]

        } -> cluster_tools_sink [style=invis,minlen=0]

        myc -> cred_store

        intrepid -> sevenzip
        intrepid -> hg
        intrepid -> svn [weight=10]
        devenv -> VS

    }

    subgraph cluster_platform {
        label="Platform"
        node [color=darkgreen, fontcolor=darkgreen, style=diagonals]

        cluster_platform_source [shape=point,margin="0.0",style=invis]
        cluster_platform_sink [shape=point,margin="0.0",style=invis]
        cluster_platform_source -> {

            Java [label="Java 7"]
            Windows

        } -> cluster_platform_sink [style=invis,minlen=0]

        Gradle -> Groovy -> Java
        https_kit -> Gradle [weight=7]
        https_kit -> Windows
        custom_gradle -> Gradle
    }

    cluster_project_sink -> cluster_plugins_source [style=invis, weight=3]
    cluster_plugins_sink -> cluster_distro_source [style=invis, weight=3]
    cluster_kits_sink -> cluster_distro_source [style=invis, weight=3]
    cluster_plugins_sink -> cluster_kits_source [style=invis, weight=3] // just for layout
    cluster_plugins_sink -> cluster_tools_source [style=invis, weight=3]
    cluster_tools_sink -> cluster_kits_source [style=invis, weight=3] // just for layout
    cluster_plugins_sink -> cluster_platform_source [style=invis, weight=3]
    cluster_distro_sink -> cluster_platform_source [style=invis, weight=3]
}
--
