package holygradle.custom_gradle.plugin_apis

/**
 * An interface for plugins which can stamp strings into existing text files.
 */
interface StampingProvider {
    /**
     * Sets the name for the task which will be generated by the provider.
     *
     * @param taskName The name for the task which will be generated by the provider.
     */
    fun setTaskName(taskName: String)

    /**
     * Returns the name for the task which will be generated by the provider.
     * @return The name for the task which will be generated by the provider.
     */
    fun getTaskName(): String

    /**
     * True if the stamping should be done before a DevEnv build; false if it should happen after.
     */
    fun getRunPriorToBuild(): Boolean
}