package holygradle.custom_gradle.plugin_apis

/**
 * An interface for plugins which can stamp strings into existing text files.
 */
interface StampingProvider {
    /**
     * Returns the name for the task which will be generated by the provider.
     * @return The name for the task which will be generated by the provider.
     */
    var taskName: String

    /**
     * True if the stamping should be done before a DevEnv build; false if it should happen after.
     */
    var runPriorToBuild: Boolean
}